//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_library
{
    using System;
    using System.Collections.Generic;
    
    public partial class loan
    {
        public int loan_id { get; set; }
        public string loantype { get; set; }
        public int amount { get; set; }
        public int duration { get; set; }
        public int rateofintrest { get; set; }
        public int borrower_b_id { get; set; }
    
        public virtual borrower borrower { get; set; }
    }
}
